### ISSUE TITLE
Error during initial set up - maybe firewall/network proxy issue?

### ISSUE THREAD

**Issue by batesmotel34** [aws-samples/amazon-cognito-api-gateway#1]
The set up step: bash ./helper.sh open-cognito-ui

fails with the error: 
......Couldn't get a file descriptor referring to the console

after displaying the username and generated password. 

Is an http server running on localhost required for the url http://localhost to be used? If so, this should be indicated in the README.md instructions.

**Comment by lovaarte** [comment]
Hi @batesmotel34, no there no local server. It's just after you login into Cognito successfully, it redirects you to localhost and you can see the credentials.
It sounds like [L205](https://github.com/aws-samples/amazon-cognito-api-gateway/blob/c282bd9083bc6630c79f8137dfde3b8fc5b4ce1c/helper.sh#L205) is where you get an issue. Can it be something is configured on your machine so that "open" command doesn't open a browser for you? try to run the command in debug mode "bash -x ./helper.sh open-cognito-ui", it will print the ${COGNITO_UI_URL} variable, try to paste it in your browser and proceed with login.

**Comment by batesmotel34** [comment]
Thanks for your quick reply. I was running this on a linux ec2 instance and it turns out no browser was installed there so there was no default app able to open the url. I got it working with ubuntu running under wsl2 on my laptop.  Minor issue there is that bash on ubuntu doesn't have an open command but changing helper.sh to use xdg-open solved that. 
   
  
  
   
  
  
   Thanks again. 
  
  
   
  
  
   Chris
  
  
   
    On 03/22/2022 6:37 PM Artem Lovan ***@***.***> wrote:
   
   
    
   
   
    
   
   
   Hi @batesmotel34, no there no local server. It's just after you login into Cognito successfully, it redirects you to localhost and you can see the credentials.It sounds like L205 is where you get an issue. Can it be something is configured on your machine so that "open" command doesn't open a browser for you? try to run the command in debug mode "bash -x ./helper.sh open-cognito-ui", it will print the ${COGNITO_UI_URL} variable, try to paste it in your browser and proceed with login.

**Comment by lovaarte** [comment]
Ok, that's great. I'll push a change to better handle this use case. Something that will try to open and it fails will notify/print and provide guidance what to do. Thanks for bringing that up!
